final Map<String, List<int>> topicHymns = {
  "하나님": [...List.generate(13, (i) => i + 1), ...List.generate(5, (i) => i + 373)],
  "예수 그리스도": [...List.generate(34, (i) => i + 14), ...List.generate(14, (i) => i + 378)],
  "찬양": List.generate(10, (i) => i + 48),
  "주님의 고난": [...List.generate(21, (i) => i + 58), ...List.generate(11, (i) => i + 392)],
  "부활": List.generate(13, (i) => i + 79),
  "복음과 구원": List.generate(18, (i) => i + 92),
  "경배와 찬양": [...List.generate(46, (i) => i + 110), ...List.generate(54, (i) => i + 403)],
  "예배": [...List.generate(57, (i) => i + 156), ...List.generate(3, (i) => i + 457)],
  "은혜와 사랑": [...List.generate(61, (i) => i + 213), ...List.generate(50, (i) => i + 460)],
  "믿음과 확신": List.generate(10, (i) => i + 274),
  "확신과 간증": [...List.generate(15, (i) => i + 284), ...List.generate(11, (i) => i + 510)],
  "찬양과 간증": [...List.generate(14, (i) => i + 299), ...List.generate(6, (i) => i + 521)],
  "평안과 위로": List.generate(13, (i) => i + 313),
  "인도와 보호": [...List.generate(16, (i) => i + 326), ...List.generate(8, (i) => i + 563)],
  "헌신과 충성": [...List.generate(15, (i) => i + 342), ...List.generate(16, (i) => i + 571)],
  "장래의 소망": [...List.generate(16, (i) => i + 357), ...List.generate(2, (i) => i + 587)],
  "감사의 고백": List.generate(36, (i) => i + 527),
};