// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaSHpVAEUoIvnfN4qG7IvjljiqoS-bJDI',
    appId: '1:800123758723:android:ad7a3a813c49007c2393b6',
    messagingSenderId: '800123758723',
    projectId: 'worship-hymn',
    storageBucket: 'worship-hymn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC79vwFMZI1zH01BiojnyIJNeVmpBu7HUU',
    appId: '1:800123758723:ios:ceb659ea4763c5702393b6',
    messagingSenderId: '800123758723',
    projectId: 'worship-hymn',
    storageBucket: 'worship-hymn.firebasestorage.app',
    androidClientId: '800123758723-9lborot1bag7hq39fltj6417nsuj6dos.apps.googleusercontent.com',
    iosClientId: '800123758723-21ukafthakhir6sa24h3fm7ormg71j1f.apps.googleusercontent.com',
    iosBundleId: 'com.worship.hymn.worshipHymn',
  );

}